### ISSUE TITLE
Add some badges to README

### ISSUE THREAD

**Issue by E3V3A** [kou1okada/apt-cyg#35]
I suggest to add the following to the top of the README.
(Did not send you a new PR yet, until you merge what I already sent.)

```
## apt-cyg

[![GitHub last commit](https://img.shields.io/github/last-commit/kou1okada/apt-cyg.svg)](https://github.com/kou1okada/apt-cyg)
[![Maintenance](https://img.shields.io/badge/Maintained%3F-yes-green.svg)](https://GitHub.com/kou1okada/apt-cyg/graphs/commit-activity)
[![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/kou1okada/apt-cyg.svg)](http://isitmaintained.com//project/kou1okada/apt-cyg "Average time to resolve an issue")


**`apt-cyg`** is your friendly [Cygwin](http://cygwin.com/) package manager. The syntax is similar to *apt-get* and is a feature improved wrapper to the native Cygwin `setup.exe`.


| STATUS: | Version | Date | Maintained? |
|:------- |:------- |:---- |:----------- |
| Working | `1.0.58` | 2018-11-22 | YES |

---


```

Then add the following to the bottom of your README:

```
#### Forks on the github

See [other_forks.md](other_forks.md)

#### Todo

- [ ] Support multi mirrors: Cygwin setup can use multi mirrors. They are recorded at last-mirror section in '/etc/setup/setup.rc'. It's useful for using [Cygwinports](http://cygwinports.org/).
- [ ] Support upgrade: But maybe, busy resources can not be upgraded, and rebase problem will happen. Cygwin setup resolves by replacing them at next reboot.
- [ ] Support dependency check for remove subcommand.

#### Known Problems

For older known problems see: [**`known problems`**](known_problems.md)

---

#### Credits

Most grateful thanks to:
* [---](https://github.com/---/) - for clarifying and fixing XXXX

---

#### License

[![GitHub license](https://img.shields.io/github/license/kou1okada/apt-cyg.svg)](https://github.com/kou1okada/apt-cyg/blob/master/LICENSE) 
A license to :sparkling_heart:!
```

**Comment by kou1okada** [comment]
This suggestion is duplication or description of pull request #34.
Please write there if you have any comments to this issue.

**Comment by E3V3A** [comment]
This is different, and issues and PRs are not the same. 
(People see and comment on issues, but rarely bother looking at PR comments.)
